#!/bin/bash

rm -r build

cmake -S . -B build --toolchain wasix.cmake_toolchain \
-DBUILD_EXAMPLES=OFF \
-DBUILD_OSSFUZZ=OFF  \
-DBUILD_REGRESS=OFF  \
-DBUILD_SHARED_LIBS=OFF \
-DBUILD_TOOLS=OFF \
-DENABLE_BZIP2=OFF \
-DENABLE_COMMONCRYPTO=OFF \
-DENABLE_GNUTLS=OFF \
-DENABLE_LZMA=OFF \
-DENABLE_MBEDTLS=OFF \
-DZLIB_INCLUDE_DIR="$WASIX_ZLIB" \
-DZLIB_LIBRARY="$WASIX_ZLIB" \
-DOPENSSL_INCLUDE_DIR="$WASIX_OPENSSL/include" \
-DOPENSSL_CRYPTO_LIBRARY="$WASIX_OPENSSL" \
-DOPENSSL_SSL_LIBRARY="$WASIX_OPENSSL" && cd build && make -j12
